latency-wait: "{{cookiecutter.latency_wait}}"
use-conda: {{cookiecutter.use_conda}}
keep-going: {{cookiecutter.keep_going}}
restart-times: {{cookiecutter.restart_times}}
jobs: {{cookiecutter.jobs}}
cluster: "qsub-submit.py"
cluster-status: "qsub-status.py"
local-cores: 1
